[package]
name = "gcp-access-token"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openssl = "0.10.30"
reqwest = "0.11.8"
json = "0.12.4"
tokio = { version = "1.15.0", features = ["full"] }
